name: CD Pipeline
 
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger AWS CodeDeploy
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        APPLICATION_NAME: ${{ secrets.APPLICATION_NAME }}
        DEPLOYMENT_GROUP_NAME: ${{ secrets.DEPLOYMENT_GROUP_NAME }}
      run: |
        aws deploy create-deployment \
          --application-name $APPLICATION_NAME \
          --deployment-group-name $DEPLOYMENT_GROUP_NAME \
          --revision revisionType=GitHubLocation,gitHubLocation={repository=${{ github.repository }},commitId=${{ github.sha }}} \
          --region $AWS_REGION
