name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build # Ensure this runs only after the CI job completes successfully

    steps:
      # Checkout the repository (optional, for access to scripts or configs)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Pull the Docker image on the target server and deploy
      # - name: Deploy to Server
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     SERVER_USER: ${{ secrets.SERVER_USER }}
      #     SERVER_HOST: ${{ secrets.SERVER_HOST }}
      #   run: |
      #     # Add the server to known hosts
      #     mkdir -p ~/.ssh
      #     echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     ssh-keyscan -H "${SERVER_HOST}" >> ~/.ssh/known_hosts

      #     # SSH into the server and deploy the container
      #     ssh ${SERVER_USER}@${SERVER_HOST} "
      #       docker pull shan533/common-assessment-tool:${{ github.sha }} &&
      #       docker stop common-assessment-container || true &&
      #       docker rm common-assessment-container || true &&
      #       docker run -d --name common-assessment-container -p 8000:8000 shan533/common-assessment-tool:${{ github.sha }}
      #     "
