name: CD Pipeline
 
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
 
    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
 
      # Step 3: Pull the Latest Docker Image
      - name: Pull Latest Docker Image
        run: |
          docker pull shan533/common-assessment-tool:latest
          echo "Pulled the latest Docker image: shan533/common-assessment-tool:latest"
 
      # Step 4: Deploy to EC2
      - name: Deploy Application to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Stopping any running container..."
            sudo docker stop my-container || true
            sudo docker rm my-container || true
            echo "Starting the new container..."
            sudo docker run -d --name my-container -p 8000:8000 shan533/common-assessment-tool:latest
