name: CI Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'app/clients/**'  # Ignore all changes in the 'clients' directory
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'app/clients/**'  # Ignore all changes in the 'clients' directory

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Pylint
        run: |
          pip install pylint

      - name: Run Pylint and Save Report
        run: |
          pylint app/ --ignore=clients || true  # Continue even if pylint fails
          pylint app/ --ignore=clients > pylint-report.txt

      - name: Upload Pylint Report
        uses: actions/upload-artifact@v3
        with:
          name: pylint-report
          path: pylint-report.txt

      - name: Generate Workflow Summary
        run: |
          echo "## Pylint Results" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat pylint-report.txt >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
