name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-lint-and-docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r app/requirements.txt

      # Step 4: Run tests with pytest
      - name: Run tests
        run: |
          export PYTHONPATH=.
          pytest tests/

      # Step 5: Run linting with pylint
      - name: Run pylint
        run: |
          pylint app/ || echo "Linting completed with issues"

      # Step 6: Build Docker image
      - name: Build Docker Image
        run: docker build -t commonassessmenttool .

      # Step 7: Run Docker container
      - name: Run Docker Container
        run: docker run -d -p 8000:8000 --name app-container commonassessmenttool

      # Step 8: Test Docker container
      - name: Test Docker Application
        run: |
          sleep 10  # Allow time for the container to start
          curl http://localhost:8000 || exit 1

      # Step 9: Clean up Docker resources
      - name: Cleanup
        if: always()
        run: |
          docker stop app-container || true
          docker rm app-container || true
