name: CI Pipeline for FastAPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Pylint
      - name: Run Pylint
        run: |
          pip install pylint
          pylint app/ tests/

      # Step 5: Run Tests
      - name: Run Tests
        run: |
          pip install pytest
          pytest tests/

  docker-build-and-test:
    runs-on: ubuntu-latest
    needs: lint-and-test  # Ensures linting and testing are successful before Docker steps

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Build Docker Image
      - name: Build Docker Image
        run: docker build -t common-assessment-tool .

      # Step 3: Run Docker Container
      - name: Run Docker Container
        run: docker run -d -p 8000:8000 --name test-container common-assessment-tool

      # Step 4: Test Docker Container
      - name: Test Docker Container
        run: |
          sleep 5  # Wait for container to start
          curl -f http://localhost:8000/docs || exit 1

      # Step 5: Stop and Remove Docker Container
      - name: Clean Up Docker
        run: |
          docker stop test-container
          docker rm test-container
