name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Run tests
      - name: Run tests
        run: |
          pytest  # Replace with your preferred test command if different

      # Build Docker image
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Set in GitHub Secrets

      - name: Build Docker image
        run: |
          docker build -t my-image-name:${{ github.sha }} .

      # Push Docker image
      - name: Push Docker image
        run: |
          docker tag my-image-name:${{ github.sha }} my-dockerhub-username/my-image-name:${{ github.sha }}
          docker push my-dockerhub-username/my-image-name:${{ github.sha }}
