name: CI Pipeline for FastAPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4
      - name: Run Pylint
        run: |
          pip install pylint
          pylint app/ tests/

      # Step 5
      - name: Run Tests
        run: |
          pip install pytest
          pytest tests/
