name: Continuous Integration Pipeline

# Triggering the workflow on push or pull request to the main branch
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4.8.0
      with:
        python-version: 3.10.11
    - name: Check versions 
      run: |
        python --version
        pip --version
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run Pylint
      run: |
        pip install pylint
        pylint $(git ls-files '*.py')
    - name: Run Unit Tests
      run: |
        pip install pytest
        pytest test