name: Continuous Integration Pipeline

# Triggering the workflow on push or pull request to the main branch
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check versions 
      run: |
        python --version
        pip --version
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run Pylint
      run: |
        pip install pylint
        pylint $(git ls-files '*.py')
    - name: Run Unit Tests
      run: |
        pip install pytest
        pytest test