name: Docker CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 4: Build Docker image
    - name: Build Docker Image
      run: |
        docker build -t fastapi-app .

    # Step 5: Push Docker Image (Optional)
    - name: Push Docker Image
      run: |
        docker tag fastapi-app ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

    # Step 6: Run the container
    - name: Run Docker Container
      run: |
        docker run -d --name fastapi-container -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

    # Step 7: Test API Endpoints
    - name: Test API Endpoints
      run: |
        sleep 5 # Allow time for the container to start
        curl -f http://localhost:8000/docs
        curl -f http://localhost:8000/clients
