name: Pylint Check

on:
  push:
    branches:
      - NewBranchToTestCI # Trigger workflow on push to this branch
  pull_request:
    branches:
      - NewBranchToTestCI # Trigger workflow on pull requests to this branch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" # Replace with your Python version (e.g., '3.10')

      # Step 2.5: Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-distutils

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt  # Adjust the path if your requirements.txt is elsewhere

      # Step 4: Run pylint
      - name: Run Pylint
        run: pylint your_module_name_here # Replace with the name of your module, file, or directory
